class BackupError(Exception):
    """Exceptions raised for errors when performing a backup"""
    pass
